"""baseline: схема на момент подключения Alembic

Слепок того, что раньше создавал Base.metadata.create_all() при старте.
Для уже развёрнутых баз эта ревизия не выполняется, а проставляется
штампом — см. app/db_upgrade.py.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-07 18:38:25.226358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_sequences',
    sa.Column('prefix', sa.Text(), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('prefix')
    )
    op.create_table('device_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code_prefix', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_prefix'),
    sa.UniqueConstraint('name')
    )
    op.create_table('link_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=False),
    sa.Column('cable_category', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('line_style', sa.Text(), nullable=False),
    sa.CheckConstraint("line_style IN ('solid','dashed','dotted')"),
    sa.CheckConstraint("media_type IN ('copper','fiber','wireless','dac','other')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name')
    )
    op.create_table('topology_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('admin','editor','viewer')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vlans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vlan_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('subnet', sa.String(), nullable=True),
    sa.Column('gateway', sa.String(), nullable=True),
    sa.Column('dhcp_range', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vlan_number')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('device_type_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_template_interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('port_number', sa.Integer(), nullable=True),
    sa.Column('port_type', sa.Text(), nullable=True),
    sa.CheckConstraint("port_type IN ('access','trunk','uplink') OR port_type IS NULL"),
    sa.ForeignKeyConstraint(['template_id'], ['device_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'label')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('management_ip', sa.String(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('install_date', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('topology_group_id', sa.Integer(), nullable=True),
    sa.Column('topology_x', sa.Float(), nullable=True),
    sa.Column('topology_y', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('core','distribution','access') OR role IS NULL"),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['device_templates.id'], ),
    sa.ForeignKeyConstraint(['topology_group_id'], ['topology_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('device_tags',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'tag_id')
    )
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('port_number', sa.Integer(), nullable=True),
    sa.Column('port_type', sa.Text(), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('trunk_vlan_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('mac', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("port_type IN ('access','trunk','uplink') OR port_type IS NULL"),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'label')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_a_id', sa.Integer(), nullable=False),
    sa.Column('interface_b_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('connector_type', sa.Text(), nullable=True),
    sa.Column('length_m', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('speed_mbps', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("source IN ('manual','snmp','lldp')"),
    sa.CheckConstraint('interface_a_id <> interface_b_id'),
    sa.ForeignKeyConstraint(['interface_a_id'], ['interfaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interface_b_id'], ['interfaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['link_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interface_a_id'),
    sa.UniqueConstraint('interface_b_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    op.drop_table('interfaces')
    op.drop_table('device_tags')
    op.drop_table('devices')
    op.drop_table('device_template_interfaces')
    op.drop_table('device_templates')
    op.drop_table('audit_log')
    op.drop_table('vlans')
    op.drop_table('users')
    op.drop_table('topology_groups')
    op.drop_table('tags')
    op.drop_table('link_templates')
    op.drop_table('device_types')
    op.drop_table('code_sequences')
    # ### end Alembic commands ###
