"""Блокировка пользователя и требование сменить пароль

is_active — мягкая блокировка вместо удаления: audit_log ссылается на
пользователя, и записи об изменениях не должны терять автора.

must_change_password взводится администратору, созданному при первом запуске,
и после сброса пароля другим админом. Существующим пользователям флаг не
ставится: они свои пароли задавали сами.

Revision ID: 0003_user_accounts
Revises: 0002_native_types
Create Date: 2026-08-08 08:03:27.544876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_user_accounts'
down_revision: Union[str, None] = '0002_native_types'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
