"""Цвет узла на схеме, задаваемый в шаблоне устройства

Цвет живёт на модели техники, а не на устройстве: одна настройка красит все
экземпляры этой модели, и заполнять поле у каждой из тысячи железок не нужно.

Revision ID: 0004_template_color
Revises: 0003_user_accounts
Create Date: 2026-08-08 08:27:14.557150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_template_color'
down_revision: Union[str, None] = '0003_user_accounts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_templates', sa.Column('color', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_templates', 'color')
    # ### end Alembic commands ###
